#  Numpy

### Lists vs Numpy

Numpy is a multi-dimensional array library. We can store data in 1-D arrays, 2-D arrays, 3-D arrays....
The main advantage about Numpy over List is:  
(i) Numpy is very faster then List because it deals with less bytes of memory.  
(ii) No type checking when iterating through objects.  
(iii) Numpy utilises contigous memory(you would have to mention the tsrat location,the toal size and type of memory block).RThe advantage is we can use the Simd vector processing unit and effective utilisatutilization of the cache memory.  


#### Storing Difference

5 in computers is reprented as 00000101  
Using Numpy we would use Int32 format by default to store a number:  
00000000 00000000 00000000 00000101

To represnt 5 we dont really need to use 4 Bytes of data.We can use just 2 Bytes or even better 1 Byte.  
We need to specify that as Int16: 
00000000 00000101  
We need to specify that as Int8: 
00000101

Lists make use of the by default built-in int data-type which has 4 things: (i) size (ii) Reference Count (iii) Object Type (iv) Object Value 

size --> the size of integer value
Reference Count --> the number of times the integer is specifically being pointed to
Object Type --> the type
Object Value --> bits associated with it

size (4 Bytes)
Reference Count (8 Bytes)
Object Type  (8 Bytes)
Object Value (8 Bytes)

### Applications of Numpy

1) Mathematics(MATLAB Replacement)  
2) Plotting  
3) Backend  
4) Machine Learning  

## Load Necessary Libraries

In [1]:
import numpy as np

### Basics

In [2]:
# How to initialize an array (by default int32)
a =np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# How to initialize an array (setting default as I want as int16)
r =np.array([1,2,3],dtype='int16')
print(r)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


Dimension = 1D,2D..  

Shape in case of 1D will return the no of elements..  
Shape= [#rows,#columns] in case of > 1D array

In [5]:
##Get dimension of numpy array a
a.ndim

1

In [6]:
#Get dimension of numpy array b
b.ndim

2

In [7]:
#Get Shape of numpy array a
a.shape

(3,)

In [8]:
#Get Shape of numpy array b
b.shape

(2, 3)

In [9]:
# Get the Type of numpy array a
a.dtype

dtype('int32')

In [10]:
# Get the Type of numpy array r
r.dtype

dtype('int16')

In [11]:
# Get the Size of numpy array a
a.itemsize

4

ndim = 1D,2D..  
dtype = datatype(int32,int16..)  
shape= row,column >1D  for less than 1D ---> no of elements  
itemsize = how much space each element occupies  
size= how many elements are there  

In [12]:
# Get the Size of numpy array r
r.itemsize

2

In [13]:
# Get Total Size:

#m1 no of items in a * sise of each item
a.size*a.itemsize

12

In [14]:
#m2
a.nbytes

12

In [15]:
# Floats itemsize=8 whileints item size is 4(by default)
b.itemsize

8

### Accessing/Changing specific elements,rows,columns

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
# Getting no of rows and columns
a.shape

(2, 7)

In [18]:
# Get a specific element [r,c] eg.13
#m1:
a[1,5]
print(a[1,5])

#m2:
a[1,-2]
print(a[1,-2])

13
13


In [19]:
#WRONG APPROACH (giving incorrect answer)

#1st row
print(a[0])
print()
#2nd row
print(a[1])

[1 2 3 4 5 6 7]

[ 8  9 10 11 12 13 14]


## Focus on commas [ not : ]

In [20]:
# Get a specific row 
# 1st Row
a[0,:]
print(a[0,:])

print("Line-Break")

# 2nd Row
a[1,:]
print(a[1,:])

[1 2 3 4 5 6 7]
Line-Break
[ 8  9 10 11 12 13 14]


In [21]:
# Get a specific column
# 1st Col
a[:,0]
print("1st Col = ",a[:,0])

print()

# 2nd Col
a[:,1]
print("2nd Col = ",a[:,1])

print()

# 3rd Col
a[:,2]
print("3rd Col = ",a[:,2])

print()

# 4th Col
a[:,2]
print("4th Col = ",a[:,3])

print()

# 5th Col
a[:,2]
print("5th Col = ",a[:,4])
print()

# 6th Col
a[:,2]
print("6th Col = ",a[:,5])

print()

# 7th Col
a[:,2]
print("7th Col = ",a[:,6])

1st Col =  [1 8]

2nd Col =  [2 9]

3rd Col =  [ 3 10]

4th Col =  [ 4 11]

5th Col =  [ 5 12]

6th Col =  [ 6 13]

7th Col =  [ 7 14]


In [22]:
# Getting a little more fancy [startindex:endindex:stepsize]
# eg To get every  other element between 2 and 6
#m1- 0th row, column index 1 to 6(not 5 because upper limit not included) increment index by 2.
a[0,1: 6:2]

#m2-
a[0,1: -1:2]

array([2, 4, 6])

In [23]:
# Changing element at a particular loc to something else
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
# Changing entire column to something else
a[:,2]=5
print(a)

print()

a[:,2]= [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3D Example

In [25]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
b.ndim

3

In [27]:
#Getting a specific element(work outside in)
#eg(4)

b[0,1,1]

4

In [28]:
#Trial question: 1
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [29]:
#Trial question: 2
b[:,0,:]

array([[1, 2],
       [5, 6]])

### Doubts (use of : in numpy arrays)

In [30]:
#Trial question: 3
b[:0:]

array([], shape=(0, 2, 2), dtype=int32)

In [31]:
#Trial question: 4
b[:1:]

array([[[1, 2],
        [3, 4]]])

In [32]:
#Trial question: 4
b[:,0,0]

array([1, 5])

In [33]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

#### By default np.zeros and np.ones produce float64 elements  
#### By default np.full produces int32 elements

In [34]:
# All 0's matrix
np.zeros(5)

#np.zeros(5).dtype --->float64 as output 

array([0., 0., 0., 0., 0.])

In [35]:
# All 0's matrix (3d)
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
# All 0's matrix (4d)
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [37]:
# All 0's matrix (2d)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# All 1's matrix (3d)
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [39]:
# All 1's matrix (3d)
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [40]:
# Any other number (np.full(shape),number)
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [41]:
# Any other number (full_like)
# using the shape of Accessing/Changing specific elements,rows,columns

#m1-
np.full_like(a,4)

#m2- (a array ke shape me saare elements 4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.98404265, 0.25236141],
       [0.01522933, 0.5532355 ],
       [0.30159811, 0.00124084],
       [0.10425021, 0.90371624]])

In [43]:
# Random decimal numbers with sahape from another array
np.random.random_sample(a.shape)

array([[0.30785116, 0.40578741, 0.13159415, 0.03333422, 0.35218783,
        0.08438136, 0.22028316],
       [0.69827905, 0.84784787, 0.45874859, 0.53640634, 0.21952706,
        0.3164846 , 0.46318591]])

In [44]:
# Random Integer Values
#(the upper limit for random values i.e all values are generated randomly and they are less than this upper limit, shape/size)
np.random.randint(7,size=(3,3))

array([[2, 4, 3],
       [0, 5, 6],
       [1, 6, 4]])

#### Upper limit is exclusive but lower limit is inclusive 

In [45]:
# Random integers where lower and upper limit for randomness specified
np.random.randint(-10,0,size=(3,3))

array([[-3, -3, -6],
       [-6, -2, -8],
       [-1, -3, -9]])

In [46]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
# Repeat Array
arr= np.array([1,2,3])
r1=np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [48]:
# Repeat Array
arr1= np.array([[1,2,3]])
r1=np.repeat(arr1,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
# Repeat Array
arr1= np.array([[1,2,3]])
r1=np.repeat(arr1,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [50]:
# My Approach
array=np.ones([5,5],dtype='int32')
print(array)
print()

array[1,1:4]=[0,0,0]
print(array)
print()

array[3,1:4]=[0,0,0]
print(array)
print()

array[2,1:4:2]=[0,0]
print(array)
print()

array[2,2]=9
print(array)
print()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]



In [51]:
# Best Approach
output=np.ones((5,5),dtype='int32')
print(output)
print()

z=np.zeros((3,3),dtype='int32')
print(z)
print()

z[1,1]=9
print(z)
print()

output[1:4,1:4]=z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 9 0]
 [0 0 0]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful when copying arrays!!!

In [52]:
a=np.array([1,2,3])
b=a
b
#Now though we are making changes to b(copy of a) they are getting reflected in a
b[0]=100
print("Before copy function")
print(b)
print(a)
print()

#To prevent that we use the copu function
a=np.array([1,2,3])
c=a.copy()
c
c[0]=100
print("After copy function")
print(c)
print(a)

Before copy function
[100   2   3]
[100   2   3]

After copy function
[100   2   3]
[1 2 3]


### Mathematics

In [53]:
#Adds 2 to each element
a=np.array([1,2,3,4])
print('a+2',a+2)
print()

#Adds 2 to each element
a=np.array([1,2,3,4])
print('a-2',a-2)
print()

#Adds 2 to each element
a=np.array([1,2,3,4])
print('a*2',a*2)
print()

#Adds 2 to each element
a=np.array([1,2,3,4])
print('a/2',a/2)
print()

a+2 [3 4 5 6]

a-2 [-1  0  1  2]

a*2 [2 4 6 8]

a/2 [0.5 1.  1.5 2. ]



In [54]:
# Adding 2 numpy arrays
a=np.array([1,2,3,4])
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [55]:
a.dtype

dtype('int32')

In [56]:
# a to the power 2 (a^2)
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [57]:
# Computing sin of all values
print('sin',np.sin(a))
print()


# Computing cos of all values
print('cos',np.cos(a))
print()


sin [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]

cos [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]



### Linear Algebra

In [58]:
a=np.ones((2,3))
print('shape of a:',a.shape)
print(a)
print()
b=np.full((3,2),2)
print('shape of b:',b.shape)
print(b)
print()

# Thus no of col in 1st matrix=3=no of col in 2nd matrix
#Dimension of product Matrix=(2,2)
np.matmul(a,b)

shape of a: (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]

shape of b: (3, 2)
[[2 2]
 [2 2]
 [2 2]]



array([[6., 6.],
       [6., 6.]])

In [59]:
# Finding the dtermintant matrix
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [60]:
stats=np.array([[1,2,3],[4,5,6]])
stats

#Finding min
min=np.min(stats)
print('min=',min)

#Finding max
max=np.max(stats)
print('max=',max)

#Finding min row-wise
minrow=np.min(stats,axis=1)
print('minrow=',minrow)

#Finding min col-wise
mincol=np.min(stats,axis=0)
print('mincol=',mincol)

#Finding max row-wise
maxrow=np.max(stats,axis=1)
print('maxrow=',maxrow)

#Finding max col-wise
maxcol=np.max(stats,axis=0)
print('maxcol=',maxcol)

#Sum
sum=np.sum(stats)
print('sum=',sum)

#Sum row-wise
sumrow=np.sum(stats,axis=1)
print('sum=',sumrow)

#Sum col-wise
sumcol=np.sum(stats,axis=0)
print('sum=',sumcol)

min= 1
max= 6
minrow= [1 4]
mincol= [1 2 3]
maxrow= [3 6]
maxcol= [4 5 6]
sum= 21
sum= [ 6 15]
sum= [5 7 9]


### Reorganizing Arrays

In [61]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print("before=",before)
print()

before_shape=before.shape
print('Before shape=',before_shape)
print()

#Reshaping matrix (2,4)--->(8,1)
after=before.reshape((8,1))
print("after=",after)
print()

#Reshaping matrix (2,4)--->(4,2)
before=np.array([[1,2,3,4],[5,6,7,8]])
after1=before.reshape((4,2))
print("after1=",after1)
print()

#Reshaping matrix (2,4)--->(2,2,2)
before=np.array([[1,2,3,4],[5,6,7,8]])
after2=before.reshape((2,2,2))
print("after2=",after2)
print()

before= [[1 2 3 4]
 [5 6 7 8]]

Before shape= (2, 4)

after= [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

after1= [[1 2]
 [3 4]
 [5 6]
 [7 8]]

after2= [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [62]:
# Vertically Stacking Vectors
# As long as no of columns is same in both arrays to be stacked,their rows may differ..
v1 = np.array([1,2,3,4])
v2 = np.array([[5,6,7,8],[2,4,6,8]])

#eg1
print(np.vstack([v1,v2]))

print()

#eg2
print(np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]
 [5 6 7 8]
 [2 4 6 8]
 [5 6 7 8]
 [2 4 6 8]]


In [63]:
# Horizontal Stack
h1=np.ones((2,4))
print(h1)
print()

h2=np.zeros((2,2))
print(h2)
print()

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0.]
 [0. 0.]]



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from File

In [64]:
#automatically casts it to float type
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata)
print()
print(filedata.dtype)
print()
#now changing the data type to integer (float62--->int32).So it makes a copy and does not affect the original
filedata_int=filedata.astype('int32')
print(filedata_int)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]

float64

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking & Advanced Indexing

In [65]:
#Places in Filedata where condition is true will return as True and the rest will return as False
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [66]:
#Getting the values where the condition is true
filedata_int[filedata_int >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [67]:
### You can index with a list in Numpy
a=np.array([1,2,3,4,5,6,7,8,9])
#To get the numbers 2 3 9
a[[1,2,8]]

array([2, 3, 9])

In [68]:
# Since axis=0, we will go column wise..there are a total of 18 columns so 18 values in result
#In any function even if 1 value in the column satisfies the conditon the column gets true
np.any(filedata >50,axis=0)
#1st col no value>50
#2nd col no value>50
#3rd col no value>50
#4th col no value>50
#5th col True
#6th col True
#7th col no value>50
#8th col True
#9th col True
#10th col no value>50
#11th col no value>50
#12th col no value>50
#13th col no value>50
#14th col no value>50
#15th col no value>50
#16th col no value>50
#17th col True
#18th col True

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [69]:
#In all function even all values in the column must satisfy the conditon then column gets true
np.all(filedata >50,axis=0)
#1st col not all values >50
#2nd col not all values >50
#3rd col not all values >50
#4th col not all values >50
#5th col True
#6th col not all values >50
#7th col not all values >50
#8th col not all values >50
#9th col not all values >50
#10th col not all values >50
#11th col not all values >50
#12th col not all values >50
#13th col not all values >50
#14th col not all values >50
#15th col not all values >50
#16th col not all values >50
#17th col not all values >50
#18th col not all values >50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [70]:
# Since axis=1, we will go row wise..there are a total of 3 columns so 3 values in result
#In any function even if 1 value in the row satisfies the conditon the row gets true
np.any(filedata >50,axis=1)
#1st Row True
#2nd Row True
#3rd Row True

array([ True,  True,  True])

In [71]:
# Since axis=1, we will go row wise..there are a total of 3 columns so 3 values in result
#In all function even all values in the row must satisfy the conditon then row gets true
np.all(filedata >50,axis=1)
#1st Row not all values >50
#2nd Row not all values >50
#3rd Row not all values >50

array([False, False, False])

In [72]:
# Conditions in Numpy very similar to Pandas
((filedata > 50) & (filedata < 100))
#Adding not symbol
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [95]:
test=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
test

#To get values 11 12 16 17
print(test[2:4,0:2])
print()

#To get values 2 8 14 20
printer=test[[0,1,2,3],[1,2,3,4]]
print(printer)
print()

#To get values 4 5 24 25 29 30
#m1
p=test[[0,0,4,4,5,5],[3,4,3,4,3,4]]
print(p)
print()

#m2
p1=test[[0,4,5],3:]
print(p1)

[[11 12]
 [16 17]]

[ 2  8 14 20]

[ 4  5 24 25 29 30]

[[ 4  5]
 [24 25]
 [29 30]]


In [74]:
test[4:-1,3:-1]

array([[24]])

### References

In [75]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
# Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...